before_install:
  - if [[ `gem -v` != 1.8.* ]]; then gem update --system; fi
script: "script/test_all 2>&1 && bin/rake cucumber --backtrace 2>&1"
bundler_args: "--binstubs .bundle/bin --path vendor"
language: ruby
rvm:
  - '1.9.2'
#  - '1.9.3'
#  - '1.8.7'
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-18mode
#  - rbx-19mode
#  - ree
# uncomment this line if your project needs to run something other than `rake`:
#script: bundle exec rspec spec
#matrix:
#  allow_failures:
#    - rvm: jruby-18mode
#    - rvm: jruby-19mode
#    - rvm: rbx-19mode
#    - rvm: rbx-18mode
